### ISSUE TITLE
Hashboard do not report temps

### ISSUE THREAD

**Issue by dfoderick** [taserz/S9-Volt-Rocket-Ship#2]
This is a known problem with your mining software.

It is critical that this issue gets fixed because users need to adjust the frequency depending on the temperature of the boards.

**Comment by taserz** [comment]
That was fixed a while ago. The issue only persists if you don't follow the instructions properly. I will update the thread.

**Comment by dfoderick** [comment]
Thanks for quick response.
I should add that I am using bmminer880 which was added to your repository 12 days ago.
I have not tried any of the newer ones.

**Comment by taserz** [comment]
Which model S9 are you using? I also do have a thermal threshold set for all the hashboards enabled if one asic goes above the threshold.

**Comment by dfoderick** [comment]
S9 13.5, I think I bought this one in Febrary and it came with November 2017 FW
Here is system overview with your bmminer running. 

Miner Type | Antminer S9
-- | --
Hostname | antMiner
Model | GNU/Linux
Hardware Version | 16.8.1.3
Kernel Version | Linux 3.14.0-xilinx-ge8a2f71-dirty #82 SMP PREEMPT Tue May 16 19:49:53 CST 2017
File System Version | Fri Nov 17 17:37:49 CST 2017
Logic Version | S9_V2.54
BMminer Version | 2.0.0
Uptime | 6
Load Average | 0.07, 0.17, 0.21

**Comment by taserz** [comment]
Can you send the kernal log. Did you also flash the 650m fixed firmware prior to swapping out bmminer.

**Comment by dfoderick** [comment]
No, I did not flash the fixed firmware. I thought that was optional.
I will try that and report back.
Here the kernel log WITHOUT 650m, I set frequency to 700

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 3.14.0-xilinx-ge8a2f71-dirty (lzq@armdev2) (gcc version 4.8.3 20140320 (prerelease) (Sourcery CodeBench Lite 2014.05-23) ) #82 SMP PREEMPT Tue May 16 19:49:53 CST 2017
[    0.000000] CPU: ARMv7 Processor [413fc090] revision 0 (ARMv7), cr=18c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] Machine model: Xilinx Zynq
[    0.000000] cma: CMA: reserved 128 MiB at 27800000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 258048
[    0.000000] free_area_init_node: node 0, pgdat c0740a40, node_mem_map e6fd8000
[    0.000000]   Normal zone: 1520 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 194560 pages, LIFO batch:31
[    0.000000]   HighMem zone: 496 pages used for memmap
[    0.000000]   HighMem zone: 63488 pages, LIFO batch:15
[    0.000000] PERCPU: Embedded 8 pages/cpu @e6fc0000 s9088 r8192 d15488 u32768
[    0.000000] pcpu-alloc: s9088 r8192 d15488 u32768 alloc=8*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 256528
[    0.000000] Kernel command line: noinitrd mem=1008M console=ttyPS0,115200 root=ubi0:rootfs ubi.mtd=1 rootfstype=ubifs rw rootwait
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 884148K/1032192K available (5032K kernel code, 283K rwdata, 1916K rodata, 204K init, 258K bss, 148044K reserved, 253952K highmem)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xfff00000 - 0xfffe0000   ( 896 kB)
[    0.000000]     vmalloc : 0xf0000000 - 0xff000000   ( 240 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xef800000   ( 760 MB)
[    0.000000]     pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
[    0.000000]     modules : 0xbf000000 - 0xbfe00000   (  14 MB)
[    0.000000]       .text : 0xc0008000 - 0xc06d1374   (6949 kB)
[    0.000000]       .init : 0xc06d2000 - 0xc0705380   ( 205 kB)
[    0.000000]       .data : 0xc0706000 - 0xc074cf78   ( 284 kB)
[    0.000000]        .bss : 0xc074cf84 - 0xc078d9fc   ( 259 kB)
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] 	Dump stacks of tasks blocking RCU-preempt GP.
[    0.000000] 	RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=2.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] ps7-slcr mapped to f0004000
[    0.000000] zynq_clock_init: clkc starts at f0004100
[    0.000000] Zynq clock init
[    0.000015] sched_clock: 64 bits at 333MHz, resolution 3ns, wraps every 3298534883328ns
[    0.000304] ps7-ttc #0 at f0006000, irq=43
[    0.000610] Console: colour dummy device 80x30
[    0.000647] Calibrating delay loop... 1325.46 BogoMIPS (lpj=6627328)
[    0.040208] pid_max: default: 32768 minimum: 301
[    0.040429] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.040451] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.042575] CPU: Testing write buffer coherency: ok
[    0.042925] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.042985] Setting up static identity map for 0x4c4b00 - 0x4c4b58
[    0.043210] L310 cache controller enabled
[    0.043230] l2x0: 8 ways, CACHE_ID 0x410000c8, AUX_CTRL 0x72760000, Cache size: 512 kB
[    0.121038] CPU1: Booted secondary processor
[    0.210228] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.210357] Brought up 2 CPUs
[    0.210377] SMP: Total of 2 processors activated.
[    0.210385] CPU: All CPU(s) started in SVC mode.
[    0.211034] devtmpfs: initialized
[    0.213444] VFP support v0.3: implementor 41 architecture 3 part 30 variant 9 rev 4
[    0.214648] regulator-dummy: no parameters
[    0.222335] NET: Registered protocol family 16
[    0.224620] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.226898] cpuidle: using governor ladder
[    0.226913] cpuidle: using governor menu
[    0.234347] syscon f8000000.ps7-slcr: regmap [mem 0xf8000000-0xf8000fff] registered
[    0.235866] hw-breakpoint: found 5 (+1 reserved) breakpoint and 1 watchpoint registers.
[    0.235880] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.235994] zynq-ocm f800c000.ps7-ocmc: ZYNQ OCM pool: 256 KiB @ 0xf0080000
[    0.257660] bio: create slab <bio-0> at 0
[    0.259086] vgaarb: loaded
[    0.259799] SCSI subsystem initialized
[    0.260831] usbcore: registered new interface driver usbfs
[    0.261001] usbcore: registered new interface driver hub
[    0.261357] usbcore: registered new device driver usb
[    0.261877] media: Linux media interface: v0.10
[    0.262033] Linux video capture interface: v2.00
[    0.262270] pps_core: LinuxPPS API ver. 1 registered
[    0.262282] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.262403] PTP clock support registered
[    0.262759] EDAC MC: Ver: 3.0.0
[    0.263803] Advanced Linux Sound Architecture Driver Initialized.
[    0.266639] DMA-API: preallocated 4096 debug entries
[    0.266653] DMA-API: debugging enabled by kernel config
[    0.266728] Switched to clocksource arm_global_timer
[    0.287626] NET: Registered protocol family 2
[    0.288278] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.288375] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.288534] TCP: Hash tables configured (established 8192 bind 8192)
[    0.288594] TCP: reno registered
[    0.288613] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.288667] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.288929] NET: Registered protocol family 1
[    0.289289] RPC: Registered named UNIX socket transport module.
[    0.289301] RPC: Registered udp transport module.
[    0.289310] RPC: Registered tcp transport module.
[    0.289318] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.289330] PCI: CLS 0 bytes, default 64
[    0.289768] hw perfevents: enabled with ARMv7 Cortex-A9 PMU driver, 7 counters available
[    0.291792] futex hash table entries: 512 (order: 3, 32768 bytes)
[    0.293206] bounce pool size: 64 pages
[    0.294083] jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
[    0.294288] msgmni has been set to 1486
[    0.295067] io scheduler noop registered
[    0.295079] io scheduler deadline registered
[    0.295116] io scheduler cfq registered (default)
[    0.309066] dma-pl330 f8003000.ps7-dma: Loaded driver for PL330 DMAC-2364208
[    0.309087] dma-pl330 f8003000.ps7-dma: 	DBUFF-128x8bytes Num_Chans-8 Num_Peri-4 Num_Events-16
[    0.432556] e0001000.serial: ttyPS0 at MMIO 0xe0001000 (irq = 82, base_baud = 3124999) is a xuartps
[    1.005273] console [ttyPS0] enabled
[    1.009554] xdevcfg f8007000.ps7-dev-cfg: ioremap 0xf8007000 to f0068000
[    1.017232] [drm] Initialized drm 1.1.0 20060810
[    1.034113] brd: module loaded
[    1.043490] loop: module loaded
[    1.053144] e1000e: Intel(R) PRO/1000 Network Driver - 2.3.2-k
[    1.059078] e1000e: Copyright(c) 1999 - 2013 Intel Corporation.
[    1.066933] libphy: XEMACPS mii bus: probed
[    1.071302] ------------- phy_id = 0x3625e62
[    1.076025] xemacps e000b000.ps7-ethernet: pdev->id -1, baseaddr 0xe000b000, irq 54
[    1.084634] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.091443] ehci-pci: EHCI PCI platform driver
[    1.098682] zynq-dr e0002000.ps7-usb: Unable to init USB phy, missing?
[    1.105477] usbcore: registered new interface driver usb-storage
[    1.112408] mousedev: PS/2 mouse device common for all mice
[    1.118531] i2c /dev entries driver
[    1.125447] zynq-edac f8006000.ps7-ddrc: ecc not enabled
[    1.130974] cpufreq_cpu0: failed to get cpu0 regulator: -19
[    1.136896] Xilinx Zynq CpuIdle Driver started
[    1.141731] sdhci: Secure Digital Host Controller Interface driver
[    1.147918] sdhci: Copyright(c) Pierre Ossman
[    1.152190] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.159022] mmc0: no vqmmc regulator found
[    1.163035] mmc0: no vmmc regulator found
[    1.206748] mmc0: SDHCI controller on e0100000.ps7-sdio [e0100000.ps7-sdio] using ADMA
[    1.215440] usbcore: registered new interface driver usbhid
[    1.220956] usbhid: USB HID core driver
[    1.225686] nand: device found, Manufacturer ID: 0x2c, Chip ID: 0xda
[    1.231982] nand: Micron MT29F2G08ABAEAWP
[    1.235955] nand: 256MiB, SLC, page size: 2048, OOB size: 64
[    1.241899] Bad block table found at page 131008, version 0x01
[    1.248114] Bad block table found at page 130944, version 0x01
[    1.254094] nand_read_bbt: bad block at 0x0000036e0000
[    1.259236] 3 ofpart partitions found on MTD device pl353-nand
[    1.264979] Creating 3 MTD partitions on "pl353-nand":
[    1.270139] 0x000000000000-0x000002000000 : "BOOT.bin-env-dts-kernel"
[    1.278142] 0x000002000000-0x00000b000000 : "angstram-rootfs"
[    1.285454] 0x00000b000000-0x000010000000 : "upgrade-rootfs"
[    1.294393] TCP: cubic registered
[    1.297656] NET: Registered protocol family 17
[    1.302308] Registering SWP/SWPB emulation handler
[    1.308287] regulator-dummy: disabling
[    1.312592] UBI: attaching mtd1 to ubi0
[    1.838419] UBI: scanning is finished
[    1.850059] UBI: attached mtd1 (name "angstram-rootfs", size 144 MiB) to ubi0
[    1.857140] UBI: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    1.863882] UBI: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    1.870586] UBI: VID header offset: 2048 (aligned 2048), data offset: 4096
[    1.877444] UBI: good PEBs: 1151, bad PEBs: 1, corrupted PEBs: 0
[    1.883412] UBI: user volume: 1, internal volumes: 1, max. volumes count: 128
[    1.890544] UBI: max/mean erase counter: 83/47, WL threshold: 4096, image sequence number: 1283732989
[    1.899747] UBI: available PEBs: 0, total reserved PEBs: 1151, PEBs reserved for bad PEB handling: 39
[    1.908964] UBI: background thread "ubi_bgt0d" started, PID 1080
[    1.908970] drivers/rtc/hctosys.c: unable to open rtc device (rtc0)
[    1.912852] ALSA device list:
[    1.912856]   No soundcards found.
[    1.929352] UBIFS: background thread "ubifs_bgt0_0" started, PID 1082
[    1.958363] UBIFS: recovery needed
[    2.579221] UBIFS: recovery completed
[    2.582896] UBIFS: mounted UBI device 0, volume 0, name "rootfs"
[    2.588843] UBIFS: LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[    2.597949] UBIFS: FS size: 128626688 bytes (122 MiB, 1013 LEBs), journal size 9023488 bytes (8 MiB, 72 LEBs)
[    2.607838] UBIFS: reserved for root: 0 bytes (0 KiB)
[    2.612867] UBIFS: media format: w4/r0 (latest is w4/r0), UUID C72F8006-6DFF-46BA-BBE9-380960A89F92, small LPT model
[    2.624162] VFS: Mounted root (ubifs filesystem) on device 0:11.
[    2.631351] devtmpfs: mounted
[    2.634453] Freeing unused kernel memory: 204K (c06d2000 - c0705000)
[    3.482873] random: dd urandom read with 0 bits of entropy available
[    3.876742] 
[    3.876742] bcm54xx_config_init
[    4.486772] 
[    4.486772] bcm54xx_config_init
[    8.487599] xemacps e000b000.ps7-ethernet: Set clk to 124999998 Hz
[    8.493705] xemacps e000b000.ps7-ethernet: link up (1000/FULL)
[   23.165544] In axi fpga driver!
[   23.168684] request_mem_region OK!
[   23.172019] AXI fpga dev virtual address is 0xf01fe000
[   23.177160] *base_vir_addr = 0x8c510
[   23.193073] In fpga mem driver!
[   23.196142] request_mem_region OK!
[   23.199767] fpga mem virtual address is 0xf3000000
[   23.986165] 
[   23.986165] bcm54xx_config_init
[   24.616075] 
[   24.616075] bcm54xx_config_init
[   28.616501] xemacps e000b000.ps7-ethernet: Set clk to 124999998 Hz
[   28.622614] xemacps e000b000.ps7-ethernet: link up (1000/FULL)
[  741.175918] random: nonblocking pool is initialized
[ 1844.443444] xemacps e000b000.ps7-ethernet: link down
[ 1913.436367] xemacps e000b000.ps7-ethernet: link up (1000/FULL)
Detect 1GB control board of XILINX
Miner Type = S9
set_reset_allhashboard = 0x0000ffff
set_reset_allhashboard = 0x00000000
set_reset_allhashboard = 0x0000ffff
set_reset_allhashboard = 0x0000ffff
Check chain[5] PIC fw version=0x03
Check chain[6] PIC fw version=0x03
Check chain[7] PIC fw version=0x03
Fix freq=700 Chain[5] voltage_pic=108 value=880
Fix freq=700 Chain[6] voltage_pic=108 value=880
Fix freq=700 Chain[7] voltage_pic=108 value=880
set_reset_allhashboard = 0x0000ffff
set_reset_allhashboard = 0x00000000
Chain[J6] has 63 asic
Chain[J7] has 63 asic
Chain[J8] has 63 asic
Chain[J6] has no freq in PIC, set default freq=700M Ooooooh you changed the clock speed... TO THE MOON!
Chain[J6] has no core num in PIC
Chain[J7] has no freq in PIC, set default freq=700M Ooooooh you changed the clock speed... TO THE MOON!
Chain[J7] has no core num in PIC
Chain[J8] has no freq in PIC, set default freq=700M Ooooooh you changed the clock speed... TO THE MOON!
Chain[J8] has no core num in PIC

They miner is set to run at a fixed frequency so we can all buy some lambos.
read PIC voltage=940 on chain[5]
Chain:5 chipnum=63
Asic[ 0]:700 
Asic[ 1]:700 Asic[ 2]:700 Asic[ 3]:700 Asic[ 4]:700 Asic[ 5]:700 Asic[ 6]:700 Asic[ 7]:700 Asic[ 8]:700 
Asic[ 9]:700 Asic[10]:700 Asic[11]:700 Asic[12]:700 Asic[13]:700 Asic[14]:700 Asic[15]:700 Asic[16]:700 
Asic[17]:700 Asic[18]:700 Asic[19]:700 Asic[20]:700 Asic[21]:700 Asic[22]:700 Asic[23]:700 Asic[24]:700 
Asic[25]:700 Asic[26]:700 Asic[27]:700 Asic[28]:700 Asic[29]:700 Asic[30]:700 Asic[31]:700 Asic[32]:700 
Asic[33]:700 Asic[34]:700 Asic[35]:700 Asic[36]:700 Asic[37]:700 Asic[38]:700 Asic[39]:700 Asic[40]:700 
Asic[41]:700 Asic[42]:700 Asic[43]:700 Asic[44]:700 Asic[45]:700 Asic[46]:700 Asic[47]:700 Asic[48]:700 
Asic[49]:700 Asic[50]:700 Asic[51]:700 Asic[52]:700 Asic[53]:700 Asic[54]:700 Asic[55]:700 Asic[56]:700 
Asic[57]:700 Asic[58]:700 Asic[59]:700 Asic[60]:700 Asic[61]:700 Asic[62]:700 
Chain:5 max freq=700
Chain:5 min freq=700

read PIC voltage=940 on chain[6]
Chain:6 chipnum=63
Asic[ 0]:700 
Asic[ 1]:700 Asic[ 2]:700 Asic[ 3]:700 Asic[ 4]:700 Asic[ 5]:700 Asic[ 6]:700 Asic[ 7]:700 Asic[ 8]:700 
Asic[ 9]:700 Asic[10]:700 Asic[11]:700 Asic[12]:700 Asic[13]:700 Asic[14]:700 Asic[15]:700 Asic[16]:700 
Asic[17]:700 Asic[18]:700 Asic[19]:700 Asic[20]:700 Asic[21]:700 Asic[22]:700 Asic[23]:700 Asic[24]:700 
Asic[25]:700 Asic[26]:700 Asic[27]:700 Asic[28]:700 Asic[29]:700 Asic[30]:700 Asic[31]:700 Asic[32]:700 
Asic[33]:700 Asic[34]:700 Asic[35]:700 Asic[36]:700 Asic[37]:700 Asic[38]:700 Asic[39]:700 Asic[40]:700 
Asic[41]:700 Asic[42]:700 Asic[43]:700 Asic[44]:700 Asic[45]:700 Asic[46]:700 Asic[47]:700 Asic[48]:700 
Asic[49]:700 Asic[50]:700 Asic[51]:700 Asic[52]:700 Asic[53]:700 Asic[54]:700 Asic[55]:700 Asic[56]:700 
Asic[57]:700 Asic[58]:700 Asic[59]:700 Asic[60]:700 Asic[61]:700 Asic[62]:700 
Chain:6 max freq=700
Chain:6 min freq=700

read PIC voltage=940 on chain[7]
Chain:7 chipnum=63
Asic[ 0]:700 
Asic[ 1]:700 Asic[ 2]:700 Asic[ 3]:700 Asic[ 4]:700 Asic[ 5]:700 Asic[ 6]:700 Asic[ 7]:700 Asic[ 8]:700 
Asic[ 9]:700 Asic[10]:700 Asic[11]:700 Asic[12]:700 Asic[13]:700 Asic[14]:700 Asic[15]:700 Asic[16]:700 
Asic[17]:700 Asic[18]:700 Asic[19]:700 Asic[20]:700 Asic[21]:700 Asic[22]:700 Asic[23]:700 Asic[24]:700 
Asic[25]:700 Asic[26]:700 Asic[27]:700 Asic[28]:700 Asic[29]:700 Asic[30]:700 Asic[31]:700 Asic[32]:700 
Asic[33]:700 Asic[34]:700 Asic[35]:700 Asic[36]:700 Asic[37]:700 Asic[38]:700 Asic[39]:700 Asic[40]:700 
Asic[41]:700 Asic[42]:700 Asic[43]:700 Asic[44]:700 Asic[45]:700 Asic[46]:700 Asic[47]:700 Asic[48]:700 
Asic[49]:700 Asic[50]:700 Asic[51]:700 Asic[52]:700 Asic[53]:700 Asic[54]:700 Asic[55]:700 Asic[56]:700 
Asic[57]:700 Asic[58]:700 Asic[59]:700 Asic[60]:700 Asic[61]:700 Asic[62]:700 
Chain:7 max freq=700
Chain:7 min freq=700

max freq = 700
set baud=1
Chain[J6] PIC temp offset=62,0,0,0,0,0,39,28
Chain[J6] chip[244] use PIC middle temp offset=0 typeID=00
Warning: Chain[J6] has no temp offset in PIC! will fix it
New offset Chain[5] chip[244] local:-64 remote:0 offset:-42 
Chain[J6] chip[244] get middle temp offset=-42 typeID=00
Chain[J7] PIC temp offset=62,0,0,0,0,0,39,28
Chain[J7] chip[244] use PIC middle temp offset=0 typeID=00
Warning: Chain[J7] has no temp offset in PIC! will fix it
New offset Chain[6] chip[244] local:-64 remote:0 offset:-42 
Chain[J7] chip[244] get middle temp offset=-42 typeID=00
Chain[J8] PIC temp offset=62,0,0,0,0,0,39,28
Chain[J8] chip[244] use PIC middle temp offset=0 typeID=00
Warning: Chain[J8] has no temp offset in PIC! will fix it
New offset Chain[7] chip[244] local:-64 remote:0 offset:-42 
Chain[J8] chip[244] get middle temp offset=-42 typeID=00
Chain[J6] set working voltage=880 [108]
Chain[J7] set working voltage=880 [108]
Chain[J8] set working voltage=880 [108]
setStartTimePoint total_tv_start_sys=534982 total_tv_end_sys=534983
restartNum = 2 , auto-reinit enabled...
do read_temp_func once...
do check_asic_reg 0x08

get RT hashrate from Chain[5]: (asic index start from 1-63)
Asic[01]=74.8760 Asic[02]=78.0300 Asic[03]=81.8720 Asic[04]=79.1380 Asic[05]=59.2570 Asic[06]=79.0370 Asic[07]=74.2390 Asic[08]=77.6780 
Asic[09]=79.1380 Asic[10]=77.5440 Asic[11]=80.1270 Asic[12]=88.5160 Asic[13]=75.4970 Asic[14]=81.5200 Asic[15]=82.8120 Asic[16]=77.7620 
Asic[17]=83.4660 Asic[18]=77.2750 Asic[19]=79.1710 Asic[20]=81.2180 Asic[21]=82.4930 Asic[22]=76.2020 Asic[23]=85.9160 Asic[24]=78.7690 
Asic[25]=80.0770 Asic[26]=81.5030 Asic[27]=76.0510 Asic[28]=75.7820 Asic[29]=78.3990 Asic[30]=79.3560 Asic[31]=78.2320 Asic[32]=76.2520 
Asic[33]=80.2110 Asic[34]=76.5870 Asic[35]=79.5240 Asic[36]=80.3960 Asic[37]=80.7990 Asic[38]=77.2080 Asic[39]=79.6580 Asic[40]=78.6010 
Asic[41]=81.7550 Asic[42]=81.1340 Asic[43]=77.9630 Asic[44]=84.3390 Asic[45]=80.2280 Asic[46]=82.5430 Asic[47]=81.5700 Asic[48]=73.0810 
Asic[49]=81.8560 Asic[50]=81.1010 Asic[51]=76.5040 Asic[52]=76.4700 Asic[53]=82.7620 Asic[54]=83.2820 Asic[55]=77.9800 Asic[56]=80.2450 
Asic[57]=77.8460 Asic[58]=77.7950 Asic[59]=75.1280 Asic[60]=78.1810 Asic[61]=81.9900 Asic[62]=82.6110 Asic[63]=72.5110 

get RT hashrate from Chain[6]: (asic index start from 1-63)
Asic[01]=76.2350 Asic[02]=78.9700 Asic[03]=79.0370 Asic[04]=80.5300 Asic[05]=79.4560 Asic[06]=78.4330 Asic[07]=78.9360 Asic[08]=80.1610 
Asic[09]=72.9470 Asic[10]=75.5310 Asic[11]=82.7110 Asic[12]=79.6910 Asic[13]=79.9760 Asic[14]=80.9830 Asic[15]=77.1580 Asic[16]=73.8700 
Asic[17]=80.2950 Asic[18]=81.7210 Asic[19]=78.7180 Asic[20]=79.9090 Asic[21]=80.1270 Asic[22]=79.1210 Asic[23]=80.0770 Asic[24]=79.3560 
Asic[25]=82.1070 Asic[26]=71.9070 Asic[27]=77.6950 Asic[28]=70.8660 Asic[29]=85.0430 Asic[30]=81.7210 Asic[31]=75.1610 Asic[32]=82.4760 
Asic[33]=82.2410 Asic[34]=78.9700 Asic[35]=78.0640 Asic[36]=78.7180 Asic[37]=77.8790 Asic[38]=73.8860 Asic[39]=83.1810 Asic[40]=78.5840 
Asic[41]=77.0240 Asic[42]=74.6920 Asic[43]=80.1440 Asic[44]=82.8790 Asic[45]=81.4190 Asic[46]=78.5840 Asic[47]=81.5870 Asic[48]=82.8120 
Asic[49]=80.4130 Asic[50]=70.9840 Asic[51]=80.3290 Asic[52]=75.7490 Asic[53]=83.2650 Asic[54]=80.1950 Asic[55]=80.2280 Asic[56]=73.5840 
Asic[57]=79.1040 Asic[58]=79.1710 Asic[59]=80.5640 Asic[60]=79.8420 Asic[61]=76.9060 Asic[62]=80.2450 Asic[63]=78.3830 

get RT hashrate from Chain[7]: (asic index start from 1-63)
Asic[01]=79.5070 Asic[02]=76.4030 Asic[03]=76.0340 Asic[04]=80.0440 Asic[05]=78.8520 Asic[06]=83.4660 Asic[07]=79.5740 Asic[08]=81.0170 
Asic[09]=81.5870 Asic[10]=83.8180 Asic[11]=79.6070 Asic[12]=82.6610 Asic[13]=79.8930 Asic[14]=79.8420 Asic[15]=76.0670 Asic[16]=43.0000 
Asic[17]=77.3930 Asic[18]=77.3930 Asic[19]=81.5030 Asic[20]=74.5740 Asic[21]=76.0670 Asic[22]=76.4200 Asic[23]=78.7010 Asic[24]=78.7350 
Asic[25]=78.1310 Asic[26]=84.1710 Asic[27]=82.6270 Asic[28]=81.9730 Asic[29]=77.2420 Asic[30]=75.8490 Asic[31]=78.8520 Asic[32]=77.6280 
Asic[33]=75.9330 Asic[34]=77.6610 Asic[35]=75.9500 Asic[36]=77.1580 Asic[37]=82.7110 Asic[38]=77.7280 Asic[39]=83.5330 Asic[40]=80.1440 
Asic[41]=80.7480 Asic[42]=79.1710 Asic[43]=76.3860 Asic[44]=80.0100 Asic[45]=82.8290 Asic[46]=74.8430 Asic[47]=40.2140 Asic[48]=82.6610 
Asic[49]=82.8450 Asic[50]=79.8590 Asic[51]=82.1910 Asic[52]=77.5440 Asic[53]=84.9430 Asic[54]=82.4090 Asic[55]=82.5940 Asic[56]=81.4530 
Asic[57]=78.5670 Asic[58]=76.8890 Asic[59]=80.7820 Asic[60]=80.2950 Asic[61]=78.6680 Asic[62]=73.7860 Asic[63]=85.9660 
Check Chain[J6] ASIC RT error: (asic index start from 1-63)
Check Chain[J7] ASIC RT error: (asic index start from 1-63)
Check Chain[J8] ASIC RT error: (asic index start from 1-63)
Done check_asic_reg
do read temp on Chain[5]
Chain[5] Chip[62] TempTypeID=00 middle offset=-42
read failed, old value: Chain[5] Chip[62] local Temp=0
read failed on Chain[5] Chip[62] middle Temp old value:0
Done read temp on Chain[5]
do read temp on Chain[6]
Chain[6] Chip[62] TempTypeID=00 middle offset=-42
read failed, old value: Chain[6] Chip[62] local Temp=0
read failed on Chain[6] Chip[62] middle Temp old value:0
Done read temp on Chain[6]
do read temp on Chain[7]
Chain[7] Chip[62] TempTypeID=00 middle offset=-42
read failed, old value: Chain[7] Chip[62] local Temp=0
read failed on Chain[7] Chip[62] middle Temp old value:0
Done read temp on Chain[7]
set FAN speed according to: temp_highest=0 temp_top1[PWM_T]=0 temp_top1[TEMP_POS_LOCAL]=0 temp_change=0 fix_fan_steps=0
set full FAN speed...
FAN PWM: 100
read_temp_func Done! Doesn't matter much since I think we are going to want to set that to 100
Why is that you ask? Because we are blasting off to the MOON!
CRC error counter=0

**Comment by taserz** [comment]
try to flash the firmware 650 fixed firmware from bitmain first make sure it is reporting under that firmware prior. We did notice this issue that when it happened it allowed hashboard that had the no temp error to start mining with them granted that is not your case as your not getting them when you were prior. So flash to 650m first and check.

**Comment by dfoderick** [comment]
Here is an update:
I flashed 650m firmware with original bitmain bmminer and temperatures are NOT reported, therefore the temperature problem is with this model S9 and the bitmain firmware.
So you can close this issue.

On that same machine I can load the BM autofreq firmware and it does report the temperatures.

In addition, on another miner S9i I flashed 650m then copied bmminer880 and it DOES show the temperature.

It seems the temperature problem is not with you or me, the problem is with that batch S9 and bitmain firmware.

A good way to diagnose the problem:
Ask user to flash 650m and verify that temperatures are reported. If not then its just not going to work.
If temps are reported with 650m then proceed with bmminer swap and frequency adjustment.

**Comment by taserz** [comment]
Awesome. If you check my GitHub you can see some of the results many of us had with overclocking.
